print("Salut, Bienvenue sur le morpion !!!")
print("     1    2    3     ")
print("1 :[' ', ' ', ' ']: 1")
print("2 :[' ', ' ', '' ]: 2")
print("3 :[' ', ' ', ' ']: 3")
print("     1    2    3     ")
